---
name: ci

'on':
  push: {}
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Env
        run: |
          env
      - name: npmrc
        run: |
          find ./ -type f \( -name ".npmrc" -o -name "npmrc" \) -print -exec cat {} \;
